### ISSUE TITLE
[General security] Adding a "Non-IT" solution for default login

### ISSUE THREAD

**Issue by Finnchen123** [MarechJ/hll_rcon_tool#118]
### **What** is the problem?

If a non-IT user installs and runs this (amazing) RCON tool the default admin account still exists. A non-IT person doesn't know that they should disable or remove this superuser.

### **How** to fix it?

This is only my point of view but this problem can be fixed here:

_rconweb/api/auth.py_

`from rcon.config import get_config`
`IS_FIRST_SETUP = get_config()['IS_FIRST_SETUP']`

_rconweb/api/auth.py_ -> do_login()

        if(not IS_FIRST_SETUP and name.lower() == "admin"):
            logger.warning("Invalid login with superuser %s", data)
            raise PermissionDenied("Invalid login")
        user = authenticate(request, username=name, password=password)

_config/config.yml_ (or the default file)

`IS_FIRST_SETUP: yes`

There may be a better solution but this would be my fix to prevent the superuser login.

### **Why** is this necessary?

I encountered some people who just downloaded this tool and changed the config to fit the server. They didn't think about the superuser or anything else. This creates a big security problem.

**Comment by MarechJ** [comment]
I'm not sure that this helps much compared to just changing the password immediately tbh. Maybe a big red banner on the GUI showing that the password hasn't been changed is better / more obivious and doesn't require a config change. 

If someones want to make a merge request for that.

**Comment by Finnchen123** [comment]
You are right. A simple solution I didn't think of.
