### ISSUE TITLE
Get Rid of Meme on Failed Login

### ISSUE THREAD

**Issue by rileyjnevins** [MarechJ/hll_rcon_tool#142]
I think it would be a good idea to remove the meme shown on the sidebar (popup) when a user fails to log in.

For me personally, being shown it once was enough to turn away from the software and seek other alternatives. Just doesn't feel like a well-thought-out or (possibly) secured platform when these images are shown to the user.

It's cool and all, but truly a useless feature that might conflict with users desire to utilize this software- or take it seriously.

**Comment by MarechJ** [comment]
This tool is not "serious" as in professional, it's not made for profit, it's free and if people don't take it seriously just because of that, well too bad for them 🤷‍♂️
