### ISSUE TITLE
Add Auto refresh to the logs view

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#21]
Add an auto refresh to the logs in the "live"page, in the same fashion as the player list.

The `AutoRefreshBar` can probably be re-used for that see `hll_rcon_tool/rcongui/src/components/PlayerView/header.js`

**Comment by aamoyg** [comment]
I can look into this if you like.

**Comment by aamoyg** [comment]
Should I fork this and make a PR or?

**Comment by aamoyg** [comment]
I just saw that it's already implemented, shall we close this?

**Comment by MarechJ** [comment]
Ye, my bad. Forgot we had a ticket for that.
