### ISSUE TITLE
auto_settings after Reboot of Server

### ISSUE THREAD

**Issue by rawbyne** [MarechJ/hll_rcon_tool#243]
Hi there, after reboot of the rcon server the system starts all services which are available on the settings website but auto_settings. Is there a way to 

1. start it as cron or via shell?
2. fix this error in code?

**Comment by cemathey** [comment]
Change autostart to true in your supervisord configuration: https://github.com/MarechJ/hll_rcon_tool/blob/master/config/supervisord.conf#L41

**Comment by rawbyne** [comment]
Thanks. Wonderful!
