### ISSUE TITLE
On Seeding - Punish time 

### ISSUE THREAD

**Issue by rawbyne** [MarechJ/hll_rcon_tool#244]
hi there. 
We have the following problem: We want to modify the seeding rules. If we set the number of "punish" to infinity (-1) in the config.yml and the punish_interval_seconds to 20, then the player in the red zone will be punished constantly after 60 seconds. Our setting of 20 seconds is not applied. Where (in which file) do we have to make adjustments to get the desired effect?

**Comment by timraay** [comment]
Punishment intervals don't apply to red zone rules due to limitations. More specifically, it looks for the player's Offensive score to increase, which happens for every 60 seconds the player has spent in enemy territory.

**Comment by rawbyne** [comment]
Thank a lot. Got it.
