### ISSUE TITLE
Enhancement - Player stats

### ISSUE THREAD

**Issue by rawbyne** [MarechJ/hll_rcon_tool#245]
Hi there,

on the public site, users are able to see kill rates and so on. It would be great appreciate players, which make teamplay and not just kills. So as example: Players, which build most garrisons, destroyed garrisons, outposts and so on (or just buildings in general). Best supplier, best officer or such statistics. 

Also if available - which player got the most promoted player.

What do you meen about it?

**Comment by timraay** [comment]
This is again something we would like to do if it were possible, but unfortunately the game does not disclose any of this information.

As a side note, while theoretically we can retrieve Combat, Offense, Defense and Support score, including it in the statistics is (currently) out of scope. If you want a scoreboard that integrates these scores, have a look at [HLL Log Utilities](github.com/timraay/HLLLogUtilities).
