### ISSUE TITLE
Schedule welcome message

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#26]
In a similar way as for the auto-broadcast we'd like to schedule Welcome message.

1. Build service, maybe re-using `broadcast.py` or make it more like a cron (so not a linear loop)
2. Build UI for it

**Comment by FlorisE** [comment]
This is useful for making variables more useful in welcome messages. Right now you need to submit the welcome message again to update the values for variables, which might be OK for more long term variables (e.g. servername, maprotation) but less for others (e.g. onlineadmins, nextmap, randomvip).

Note that the welcome messages changes instantly for players looking at the deployment screen, so updating it too often (like every second) might be a bit bothersome.

I think there should be at least two ways of scheduling the welcome message, one is on map change, the other one automatically at an interval.
