### ISSUE TITLE
Display a icon next to the player in Live and History if he is VIP

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#29]
In `rcon.recorded_commands.Rcon.get_players` add a boolean flag showing wether the players is a VIP or not.
Make sure to do it as a batch to save some processing time.

Ideally we also add that information in the history view and player profile `rcon.player_history.get_player_profile` and `rcon.player_history.get_players_by_appearance`  

In the Live and History view, display that information (using and icon or some small test), if at the time of implementation the Profile view exists, add it there as well

**Comment by MarechJ** [comment]
For the history part this was done in #35

**Comment by hoersamu** [comment]
I just realised that this already has been fully implemented
