### ISSUE TITLE
Show the current broadcast that is displayed in game on the Rcon

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#31]
The `rcon.extended_commands.Rcon.set_broadcast` method could set the current message in Redis (with an auto expiry of say 20min?)

Add an endpoint to fetch that value in `rconweb.api.views`

Display that about the Auto broadcast panel or above the Broacast input area in the Settings page

**Comment by FlorisE** [comment]
Hmm, how about adding the broadcast to the log displayed on the live page?

**Comment by MarechJ** [comment]
done
