### ISSUE TITLE
One API endpoint returning results for 2 different servers

### ISSUE THREAD

**Issue by Dorfieeee** [MarechJ/hll_rcon_tool#311]
Hey there,

I hope I'm writing about this in the right place.

When I fetch data from [POWERBITS GAMETEAM HLL #2](http://213.32.7.63:7014/api/public_info) public API to get the most recent state of the server, sometimes it provides data for one server and then for the other.

Is this some bug or some configuration fault on the side of Powerbits?

https://github.com/MarechJ/hll_rcon_tool/assets/65303812/708e40ad-f092-481a-bc33-c694c72c7d8e

Thanks

**Comment by cemathey** [comment]
Peculiar, can you look at some of these mismatched ones and look at not just the response, but also the request and show us that as well?

Does it only happen on one page in the GUI (the public stats?) or can you reproduce it anywhere else.

Can you try running it against the API itself? http://localhost:8010/api/public_info as the URL for example and see if you can reproduce it?

I spammed the API request against our live server (has two servers in the same CRCON) and I could not reproduce it.

**Comment by Dorfieeee** [comment]
> Including headers

https://github.com/MarechJ/hll_rcon_tool/assets/65303812/675a3b00-ebfd-4bbd-a903-d75a21f8915b
