### ISSUE TITLE
Docker forever restart

### ISSUE THREAD

**Issue by OlolBzH** [MarechJ/hll_rcon_tool#350]
Hello,

My defect described below : 

When server #1 configuration is not provided, then the first container's stack keep restarting. It should only play server #x even the configuration.

Hotfix : 
Purpose by Emathey  : 
In file `docker-compose-common-components.ymll` replace 

`restart: always`

by

`restart: on-failure`

PS :  `hll_rcon_tool-frontend_1-1` container is still up with this solution.

**Comment by cemathey** [comment]
I don't think we want to change this because the database migrations and other things are only run in the backend_1 container.

**Comment by OlolBzH** [comment]
Understood, thanks for the feedback.
