### ISSUE TITLE
Ban list / Blacklist export

### ISSUE THREAD

**Issue by samcrudge** [MarechJ/hll_rcon_tool#374]
Hello, 

Is there a way via API or accessing the hosted server to export the banned/ blacklist?

Many Thanks

Sam

**Comment by ElGuillermo** [comment]
yep :
/api/get_bans

**Comment by samcrudge** [comment]
Do you have docs on how to use the API? and is that exported list of ban's importable after updates

**Comment by ElGuillermo** [comment]
Sorry : the API has been constructed without (much) doc :/
"docs contributions are most welcomed"

You may get all the command available here :
http://yourcrcon:8010/api/get_api_documentation

There is no bulk upload command available in CRCON afaik, but you can use this :
https://discord.com/channels/685692524442026020/685695097349734469/1166640842321178624
