### ISSUE TITLE
Add a config to auto-ban if a player has a VAC / Game ban for less that N days

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#40]
This is an easy one, re-use the code in steam utils to get the bans and just add a hook function on CONNECT to check the guys, the call the perma bans or do nothing. 
Add an ENV variable for the number of days. 0 to disable > 0 to enable

**Comment by geekcubed** [comment]
Ideally there should be an ENV variable to configure the ban message, as this will be shown to the player when they are kicked/banned from the server.

**Comment by geekcubed** [comment]
Is there anything that can be done to get this issue over the line?  

Every single one of suspected cheaters on our server in the last few weeks has a VAC ban in the last 6 months - this would solve a lot of problems for us right now.

**Comment by timraay** [comment]
It's in the works. Currently all that's left really is some testing - making sure we don't actually ban half your playerbase. You can expect it to be part of the next update.

**Comment by MarechJ** [comment]
This is done
