### ISSUE TITLE
Handle punctations in the trigger words

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#41]
E.g If you said the word "admin" to trigger a ping you also want the below to trigger:

Admin!!! blabla is mean
Admin, I have a problem

I think a good way of implementing that would be to re-use the tokenizer code from some libs out there, for examples Elasticsearch tokenize words maybe it has a python lib with this feature exposed? Otherwise let's build it ourselves

**Comment by MarechJ** [comment]
A partial fix is in place. The only punctuation that remains unhandled is @ and !
The fix may have broken non latin language though, and we should unaccent the string for better matches

**Comment by ElGuillermo** [comment]
This one can be conseidered as "done" : https://github.com/MarechJ/hll_rcon_tool/blob/91f6b3cdc4d4b4c096d4a5ef42c2424346940da9/rcon/discord_chat.py#L131
