### ISSUE TITLE
Low prio - Run commands from chat

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#43]
Add hooks to call any commands implemented by the Rcon class  and/or in the API from the ingame chat.

Check against the steam ids of the moderators (need to check against the Django DB though, so it's adding a weird co-dependancy and will break the separation of concerns a bit, or find another way)

**Comment by ElGuillermo** [comment]
See : https://github.com/MarechJ/hll_rcon_tool/pull/678
