### ISSUE TITLE
Handle HTTPS with arbitrary domains directly from the frontend's NGINX

### ISSUE THREAD

**Issue by MarechJ** [MarechJ/hll_rcon_tool#44]

**Comment by jdesbois** [comment]
Hey @gbottieau or @MarechJ 
Wanted to check in on any update on this? interested in taking a look but didn't want to re-iterate over anything that has already been done..
Any info you can provide regarding the entry point for the code or how its exposed would also be good.

Thanks in advance

**Comment by MarechJ** [comment]
At the moment the only way is to reverse proxy the rcon from your host and add HTTPS there.
We don't have anything for serving HTTPS via the frontend image yet, gbottieau tried some stuff but without success so far.

**Comment by jdesbois** [comment]
Roger, thank you for the update! I'll take a look and see what I can work out.
Do you have any docs on how the front end is exposed? I'm not 100% in interpreting the code correctly.

Thanks again in advance

**Comment by MarechJ** [comment]
This is somewhat done already. As you can override self signed certificates as of 3.16
