### ISSUE TITLE
Scorebot Failing to Start

### ISSUE THREAD

**Issue by jordantrizz** [MarechJ/hll_rcon_tool#487]
Getting the following error, I know I'm missing something simple.

`Your scorebot Scoreboard URL is not configured, exiting`

**Comment by ElGuillermo** [comment]
Hi !
You have to configure it in the user interface (in `/settings/scorebot`).
Every setting is documented below the configuration window.

**Comment by jordantrizz** [comment]
Thanks, did some more digging and figued it out. Thanks!
