### ISSUE TITLE
Flags and Whitelist

### ISSUE THREAD

**Issue by jordantrizz** [MarechJ/hll_rcon_tool#488]
Sorry, for submitting all the issues, hopefully someone else finds them useful. For flags, you can only use emoji's, but what value do you put in for instance in whitelist? The unicode value?

```
  "whitelist_players": {
    "has_flag": [
      "whitelist"
    ],
```

**Comment by ElGuillermo** [comment]
Hi ! you can copy-paste any Unicode emoji as

`  "whitelist_flags": [
    "🚨"
  ],`

**Comment by jordantrizz** [comment]
Awesome, thanks. Did you need someone to help with documentation?

**Comment by ElGuillermo** [comment]
Sure ! There is a wiki on this github space that desperately needs to be updated ! Any help would be awesome :)
