### ISSUE TITLE
Auto Broadcast Multiple Variables Fails

### ISSUE THREAD

**Issue by jordantrizz** [MarechJ/hll_rcon_tool#498]
When using multiple variables in an auto-broadcast message, it fails. You can only use a single variable

Example 

```30 Welcome to {servername} The Next Map Is {nextmap}```

Results in

```Welcome to {servername} The Next Map Is {nextmap}```

**Comment by caranci** [comment]
I don't see this issue. What version are you using?

**Comment by jordantrizz** [comment]
Strange, so we just updated our auto broadcast, and the following seems to work fine now on 9.4.1

```
30 Welcome to {servername} || The Next Map Is {nextmap} || The map rotation is {maprotation} || We Have Admins Online = {ingame_mods} - !admin <message> || Seed and get VIP for 48 hours
```
Closing this for now.
