### ISSUE TITLE
Create Docker Images for Docker Hub

### ISSUE THREAD

**Issue by jordantrizz** [MarechJ/hll_rcon_tool#505]
I'm in the process of creating docker images for docker hub which will allow the following.

* Creation of docker-compose.yml and docker-compose-common-components.yml only, nothing else required.
* This would allow tracking of CRCON config files via git, the current install method is to git pull and rebuild which sees docker-compose.yml as being modified.
* Allow for switch between latest and test tags easily.
* Conforms to other opensource projects.
* Can be updated automatically using watchtower.

I've created the repository here: https://hub.docker.com/r/jordantrizz/crcon its not stable yet as I'm testing.

Eventually, it would be good to stop using docker-compose-common-components.yml and have defaults set for all environment variables and then provide methods to override the defaults via docker-compose.yml as there should be no reason to have two separate docker compose files. Just a docker-compose.yml and .env if you wish to.

**Comment by cemathey** [comment]
So right now we already automatically build images on Docker Hub, but only for linux/amd64. It triggers when we push a tag and builds a [backend](https://hub.docker.com/r/maresh/hll_rcon) (also used by the supervisor container) image and a [frontend](https://hub.docker.com/r/maresh/hll_rcon_frontend) image.

The repository (and the tag) for both these images is set in `.env` so people can substitute whatever repos and version they want if they want to build their own images and upgrade/downgrade easier (it used to be hard coded into the compose files).

I do agree there is room for improvement, any thoughts on https://github.com/MarechJ/hll_rcon_tool/pull/517 ?

That gets us (with github actions) automatically built images for linux/amd64, linux/arm64 and linux/arm32 (I didn't test with others as I think that covers the vast majority of common use cases).

It also changes the `redis` and `postgres` image names to be environment variables so they can be changed at will.

At that point I think the only things we have hard coded in the compose files are the server number and redis database number, we could expose those but there is a bit of a balance to strike between how much work it is for people to upgrade (they have to update their `.env` anytime we add new stuff and confusing users.

I think we could possibly get away with just making the `redis` database number match the server number ([there are 16](https://raw.githubusercontent.com/redis/redis/7.2/redis.conf) databases by default. Right now they're zero indexed but it shouldn't hurt anything to make them the same.

The server number is not exposed in `.env` but I think we could also move that, the only downside to that I can think of is people putting in stupid values for it, but there's nothing stopping people from doing that in the compose files right now.
