### ISSUE TITLE
Add 'Search players by Flag' functionality to the History Tab

### ISSUE THREAD

**Issue by bn-hall** [MarechJ/hll_rcon_tool#54]
![image](https://user-images.githubusercontent.com/67147227/98228686-d2d5be00-1f50-11eb-84ff-d4597cfdfa1d.png)

Most users seem to use a 'set' of flags (i.e. teamkilling, toxic, etc.). It would be a good feature to search by these, especially flagged player lists become longer.

A side feature would be to add 'sort by flag' to the live view (like sort by penalties). Could assign the presence of a flag a value of 1 - i.e. flagged players will appear at the top of the list when sorting `Desc. Flags`.

Also add the flag comment tooltip to the history tab view upon mouseover (behaviour already exists on the Live view).

**Comment by MarechJ** [comment]
That's in now :)
