### ISSUE TITLE
What does this line do ?

### ISSUE THREAD

**Issue by Tanjitsu** [MarechJ/hll_rcon_tool#56]
https://github.com/MarechJ/hll_rcon_tool/blob/d733292f546af4cffce73df8d9c701474048c6e1/rcongui/public/index.html#L50

My browser on direct address just presents an apache error.
I load the rcon over https: so the console complains on page load.

**Comment by MarechJ** [comment]
Not much at the moment. 
It's something old that was originally intended to get usage statistics of the rcon.
