### ISSUE TITLE
v10-rc3: Live-view does not add blacklist record on ban

### ISSUE THREAD

**Issue by LordofAgents** [MarechJ/hll_rcon_tool#614]
Hello everyone,
as discussed on discord (https://discord.com/channels/685692524442026020/685695097349734469/1269314363324497990) a blacklist entry can only be added via the history->players-tab. 

Is it possible to change the temp and permanent ban buttons to "Add blacklist-Entry" or something similar?

Thank you!

PS: I don't want to put you under any pressure with this issue, but I would like to give you the opportunity to get an overview of the current problems. Discord messages are a bad idea, too cluttered.

**Comment by Dorfieeee** [comment]
Hey.

I believe this issue has been also resolved via https://github.com/MarechJ/hll_rcon_tool/pull/632/commits/dad45e185c39eb043c8e4208e9a86bce13d1d4df

**Comment by LordofAgents** [comment]
Thank you for noticing, closing.
