### ISSUE TITLE
v10-rc3: Map-Rotation shows "Allies" on Warfare-Maps

### ISSUE THREAD

**Issue by LordofAgents** [MarechJ/hll_rcon_tool#615]
Hey everyone,

as already discussed on discord (https://discord.com/channels/685692524442026020/706075642885832764/1269305968429371495), the new v10-rc3 update now shows "Allies" on warfare maps:
![grafik](https://github.com/user-attachments/assets/f87d0da1-2dc3-4ab2-a036-7573ccea7ae8)
Is this intentional? 

Thank you for your work!

**Comment by cemathey** [comment]
Fixed, thanks!
