### ISSUE TITLE
v10-rc3: Multiple permissions for adding blacklist records

### ISSUE THREAD

**Issue by LordofAgents** [MarechJ/hll_rcon_tool#616]
Hey everyone,

after upgrading to v10-rc3, there exists two permissions: "Can add players to blacklists" and "Can add players to the blacklist". The later one seems to be obsolete, or is only needed for normal bans (which could be removed anyway).

![grafik](https://github.com/user-attachments/assets/d455877a-1883-4136-97a7-e49240d6d528)

Maybe one of these can be removed. Or, if both are needed, the description could be changed to something more clear.

Thank you!

**Comment by cemathey** [comment]
Fixed!

**Comment by LordofAgents** [comment]
Thank you!
