### ISSUE TITLE
v10-rc3: FR GUI: Allow to use personal tex history and shared standard messages

### ISSUE THREAD

**Issue by LordofAgents** [MarechJ/hll_rcon_tool#617]
Hey everyone,

the new "Blacklist Player" does not  allow to use the shared standard messages / personal text history anymore. Is it possible to add this again to the new blacklist menu? This would be amazing!

Thank you!

**Comment by Dorfieeee** [comment]
Hey.

I believe this issue has been resolved.

![image](https://github.com/user-attachments/assets/97089f4e-e347-44f6-b78d-8796c7993245)
