### ISSUE TITLE
v10-rc3: Blacklist Bug: Sync-Method can not be changed

### ISSUE THREAD

**Issue by LordofAgents** [MarechJ/hll_rcon_tool#618]
Hey everyone,

on the new v10 update, it seems to be not possible to change the sync-method for a blacklist. It immediately jumps back to the mode chosen before. 
When i create a new blacklist, it does pick up the sync method once, but if I want to change it after I created the blacklist, it jumps back to the mode chosen at creation.

Can someone confirms that please?

Thank you!

**Comment by cemathey** [comment]
Fixed, great catch thank you.
