### ISSUE TITLE
v10-rc3: Setting VIP Slots via GUI fails

### ISSUE THREAD

**Issue by LordofAgents** [MarechJ/hll_rcon_tool#619]
Hello everyone,

In the frontend, the setting for the VIP slots does not yet seem to be adapted to the new API. Currently, changing the slots leads to "400 bad requests". It seems that the argument "num" needs to be changed to "value".
![grafik](https://github.com/user-attachments/assets/1e4f8e08-ee92-4ac6-b99f-133967abe652)

Thank you!

**Comment by cemathey** [comment]
Fixed!
