### ISSUE TITLE
WebUI returns blank screen after c. 30mins

### ISSUE THREAD

**Issue by brit** [MarechJ/hll_rcon_tool#698]
I’ve installed CRCON successfully - one installation for three HLL servers. One of our test moderators has reported that having left the WebUI up for approx 30 minutes, it just returns a completely blank/white browser screen and they can’t get back into it without clearing local browser cache.

Browser is Chrome on a PC.

**Comment by Dorfieeee** [comment]
Hey, never happened to me personally. Could they open the developer tools and see what errors they're getting?

**Comment by ElGuillermo** [comment]
Happens sometime (Firefox here !), when you have a high (2000+) "last nth logs" setting and leave the browser window open for a **very** long time (~12-24h). Not really a showstopper, though : you just have to refresh the window.

**Comment by brit** [comment]
I have determined this was a permissions error in the user group the moderator was assigned to. Specifically, as returned in the browser dev console:

```
Uncaught (in promise)
    command: "get_standard_punishment_messages"
    message: "You are not authorized to do this"
    name: "Permission error"
```

This has been resolved by amending the permissions set for the relevant group.
