### ISSUE TITLE
API: Fix`do_service` response

### ISSUE THREAD

**Issue by Dorfieeee** [MarechJ/hll_rcon_tool#723]
Inconsistent response. Should be normalized to match other responses.
- old name `do_service`
- `command` attribute is always null
![image](https://github.com/user-attachments/assets/4089f74e-01ee-4af7-acfc-6b2efe325676)

**Comment by cemathey** [comment]
https://github.com/MarechJ/hll_rcon_tool/pull/743

**Comment by LordofAgents** [comment]
Fixed by #743
