### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by maximuss** [MarechJ/hll_rcon_tool#726]
I'm sorry if it's already written somewhere, but I just couldn't find it.
When I create a new user, I get the following error message when saving:
CSRF verification failed. Request aborted.
I've tried restarting the VPS but it didn't help, so now I don't know what else to do.
Thanks in advance!

**Comment by ElGuillermo** [comment]
Hi !
Make sure you've completed [this installation part](https://github.com/MarechJ/hll_rcon_tool/wiki/Installation#7-csrf-setup-required).
Then restarted CRCON folling [these commands](https://github.com/MarechJ/hll_rcon_tool/wiki/Installation#8-restart-crcon).

**Comment by maximuss** [comment]
My fault - somehow i missed that part of the instructions. Perhaps i should refrain from doing that kind of stuff when it's late and i'm tired :)
But thank you!
