### ISSUE TITLE
Seed VIP: `reward_player_message_no_vip` is used as VIP name instead of `player_name_format_not_current_vip`

### ISSUE THREAD

**Issue by kamilkamilc** [MarechJ/hll_rcon_tool#747]
Example below

![image](https://github.com/user-attachments/assets/a046aedc-ca83-403d-8cbf-d6d53aceb17f)

**Comment by ElGuillermo** [comment]
Hey ! Thanks for noticing.
This issue has already been fixed (see: https://github.com/MarechJ/hll_rcon_tool/pull/741) in the next release of CRCON !

**Comment by kamilkamilc** [comment]
Thanks!
